region: "ca-central-1"
role: "arn:aws:iam::820242914501:role/sm_default_exec_role_1drw"
tracking_server_arn: "arn:aws:sagemaker:ca-central-1:820242914501:mlflow-tracking-server/mlops-sample-domain-mlflow"
default_bucket: "sagemaker-ca-central-1-820242914501"
model_package_group_name: "AbalonePackageGroup"
deployment:
  endpoint_name: "AbalonePackageGroup-test-endpoint"
  instance_type: "ml.m5.xlarge"
  environments:
    - prd
  mode: "single"
  versions: [1]
  variant_weights: [0.6, 0.4]
monitoring:
  enabled: false
  baseline_data_path: "s3://sagemaker-ca-central-1-820242914501/AbalonePipeline/znczwlse3yoc/AbalonePreprocessData/output/train/train.csv"
  output_bucket: "sagemaker-ca-central-1-820242914501"
  schedule_expression: "cron(0 12 * * ? *)"
